name: test_task_ecommerce
description: Test task Effective Mobile

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Code generation
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

  # Internationalization
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

  # Logging
  l: ^3.2.0
  stack_trace: ^1.10.0

  # Persistence
  shared_preferences: ^2.0.15

  # Navigation
  auto_route: ^5.0.0
  beamer: ^1.5.2

  # BLoC
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0

  # Design
  breakpoint: ^1.2.0
  salomon_bottom_bar: ^3.3.1
  flutter_rating_bar: ^4.0.1

  # Network
  http: ^0.13.5

dev_dependencies:
  # code gen
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  build_web_compilers: ^3.2.5
  auto_route_generator: ^5.0.0
  flutter_gen_runner: ^4.3.0

  # testing
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  coverage: ^1.5.0
  flutter_test:
    sdk: flutter

  # analyzer
  dart_code_metrics: ^4.17.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Mark Pro
      fonts:
        - asset: assets/fonts/Mark Pro.ttf
        - asset: assets/fonts/Mark Pro Bold.ttf
        - asset: assets/fonts/Mark Pro Heavy.ttf
        - asset: assets/fonts/Mark Pro Medium.ttf

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/l10n
  output_dir: lib/src/core/generated/localization

flutter_gen:
  output: lib/src/core/generated/resources

